backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "assets/images"

collections:
  - name: resource
    label: Resource
    folder: _resources
    create: true
    slug: "{{slug}}"
    fields:
      - label: Title
        name: title
        widget: string
      - label: URL
        name: link
        widget: string
      - label: Topics
        name: topics
        required: false
        widget: relation
        collection: topic
        searchFields: ["title", "description"]
        valueField: title
        displayFields: ["title"]
        multiple: true
      - label: Subtitle
        name: subtitle
        required: false
        widget: string
      - label: Author
        name: author
        required: false
        widget: string
      - label: Source
        name: source
        required: false
        widget: string
      - label: Body
        name: body
        required: false
        widget: markdown
  - name: "topic"
    label: "Topic"
    folder: "_topics"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        required: false
        widget: "markdown"
      - label: "See"
        name: "see"
        required: false
        widget: "relation"
        collection: "topic"
        searchFields: ["title", "description"]
        valueField: "title"
        displayFields: ["title"]
        multiple: false
